### ISSUE TITLE
Does Radar Presence support same user multi device/connections?

### ISSUE THREAD

**Issue by raygerami** [zendesk/radar#117]
Please correct me if I'm wrong.  The radar user presence is a toggle mode it either indicates online or offline.  and in the docs you mentioned that it is changed either  manually by calling the set function or by tcp disconnect/connection.  So, if the user has multiple connections i.e. desktop-connection and another lets say mobile, In this case I would expect the offline would happen if both / all connections are lost.
Can you elaborate on this?
Thanks

**Comment by samshull** [comment]
There are two separate offline events, `user_offline` and `client_offline`. The `client_offline` events indicate that one of the connections has been terminated and the `user_offline` event indicates that all client connections for a specific user have been terminated.
