### ISSUE TITLE
Does Radar has client support for Android or iOS

### ISSUE THREAD

**Issue by raygerami** [zendesk/radar#118]
I know there are android and ios libraries for socket.io.  but since Radar is build on top of engine.io are there such libraries for Radar.
Thanks

**Comment by vanchi-zendesk** [comment]
We haven't really explored radar client for mobile devices yet, but it's in the future. However if you can create a simple engine.io-client from the Mobile side then radar_client javascript should work as well.

**Comment by jden** [comment]
An example of using [radar_client](https://github.com/zendesk/radar_client) on mobile is Zendesk's [Inbox](https://www.zendesk.com/inbox/) app, which uses Cordova to package a JavaScript app. There is currently no native client support.
