### ISSUE TITLE
Question about clustering

### ISSUE THREAD

**Issue by zinas** [zendesk/radar#146]
Hello,

I am considering using Radar in a node server that uses clustering. Is there some configuration in Radar that makes it easier, or do I need to handle clustering myself?

N.

**Comment by vanchi-zendesk** [comment]
Currently Radar does not use clustering. However, it is designed to work with multiple instances of the server running while connected to the same Redis instance. So, you could run multiple instances of the server on different ports, or across machines all connected to the same instance of Redis.
