### ISSUE TITLE
Tutorial code is bad

### ISSUE THREAD

**Issue by neilmiddleton** [zendesk/radar#175]
The following code from [the tutorial](https://radar.zendesk.com/index.html):

```
var fs = require('fs'),
  url = require('url'),
  http = require('http'),
  Radar = require('radar').server;

var server = http.createServer(function(req, res) {
  console.log('404', req.url);
  res.statusCode = 404;
  res.end();
});

var radar = new Radar();

var configuration = {
  redis_host: 'localhost',
  redis_port: 6379,
  port: 5000
}
radar.attach(server, configuration);
server.listen(configuration.port);
console.log('Server is listening on port ' + configuration.port);
```

fails on startup:

`throw new Error('No configuration provided');` on the `radar.attach`.

Using node 4.2.0 and radar 0.16.5

**Comment by neilmiddleton** [comment]
Seems something like this is required instead:

```
var config = {
  redis_host: 'localhost',
  redis_port: 6379,
  port: 5000,
  persistence: true
}

var fs = require('fs'),
  url = require('url'),
  http = require('http'),
  Radar = require('radar').server,
  configuration = require('radar').configurator.load(config)

var server = http.createServer(function(req, res) {
  console.log('404', req.url);
  res.statusCode = 404;
  res.end();
});

var radar = new Radar();

radar.attach(server, configuration);
server.listen(config.port);
console.log('Server is listening on port ' + config.port);
```

**Comment by jden** [comment]
@neilmiddleton thanks for opening this issue! It's in our backlog. We recently did some work to support node 4.x, and unfortunately the docs are lagging a little behind. Any other feedback is super valuable- and of course, we're always happy to review PRs :)

**Comment by jden** [comment]
I'm currently updating this. Here are some work-in-progress notes: This documentation went out of date in https://github.com/zendesk/radar/commit/ec3a8b3cd6514e9c9e74220b6ebc4ade3d0e3416#diff-ea75b530d74f94670cea053feb8b961b when we changed the way we load configuration. I'll update the tutorial with a concise example and improve configuration documentation generally.
