### ISSUE TITLE
Support authenicated Redis

### ISSUE THREAD

**Issue by neilmiddleton** [zendesk/radar#176]
Not everyone leaves their redis instances open to the world.  Add support for basic auth redis instances, such as those supplied by [heroku-redis](https://www.heroku.com/redis).

**Comment by neilmiddleton** [comment]
It seems that persistence [already supports auth](https://github.com/zendesk/persistence/blob/master/lib/connection.js#L155-L157) via `redis_auth` config, but this doesn't make it through from Radar.

**Comment by neilmiddleton** [comment]
In fact, even better, just support Redis URLs that may or may not contain basic auth.

**Comment by jden** [comment]
We already support redis URLs. I just opened a pr adding support for auth and tested using a heroku redis config url for good measure :)
