### ISSUE TITLE
Problems with vanilla Radar

### ISSUE THREAD

**Issue by neilmiddleton** [zendesk/radar#184]
I have a super simple Radar server which is returning the following error (HTTP400) within the client:

```
XMLHttpRequest cannot load https://domain.com/engine.io/?EIO=3&transport=polling&t=1446831121358-1&sid=2Xk4XVFAB6lhh8haAAAz. Response for preflight has invalid HTTP status code 400
```

my server.js looks like this: 

```
var url = require('url'),
    http = require('http'),
    Radar = require('radar').server,
    Api = require('radar').api;

var redis_url = process.env.REDIS_URL;
parsed_url = url.parse(redis_url)

var config = {
  redisUrl: redis_url,
  redis_host: parsed_url.host,
  redis_port: parsed_url.port,
  port: process.env.PORT,
  persistence: true,
}

var configuration = require('radar').configurator.load(config)

var server = http.createServer(function(req, res) {
  console.log('404', req.url);
  res.statusCode = 404;
  res.end();
});

Api.attach(server);

var radar = new Radar();
radar.attach(server, configuration);
server.listen(config.port);
console.log('Server is listening on port ' + config.port);
```

There's nothing here I would consider odd.

What's more I only see the HTTP 400 in the logs, with no exception.  Is there any way to get Radar to log exceptions here?  (nb. This is running on Heroku)

**Comment by vanchi-zendesk** [comment]
Radar uses Engine.io internally, and you can enable logging for that through: https://github.com/socketio/engine.io#debug--logging

We usually see the 400s if the load balancing is not perfect. On a many server implementation, we require sticky load balancing to route all requests from a client to the same server. 400s show up when a request ends up with a different server. `sid=2Xk4XVFAB6lhh8haAAAz` part indicates the client id and my guess is, this server does not know of this client.

**Comment by jden** [comment]
I'm going to close this issue for now. Please feel free to open another issue if there are further questions.
