### ISSUE TITLE
Accessing api.attach

### ISSUE THREAD

**Issue by nelix** [zendesk/radar#60]
Am I missing something or is the index.js returning the wrong module?
Api.attach(httpServer);
    ^
TypeError: Object #<Object> has no method 'attach

**Comment by raygerami** [comment]
Hi, I just found Radar in git and tried to start the demo.  I setup a redis server on asure which requires password, but all you examples point to redis local host and port and does not pass the password as config data.
is there any way to connect to password protected redis server.
Thanks

**Comment by samshull** [comment]
@raygerami use `redis_auth` in your configuration for the password.
